// [standard, gujarati, notes]
const consonants = [
  ['ka', 'ક', 'scold, sky'],
  ['kha', 'ખ', 'cold, cot, emphasised version of ક'],
  ['ga', 'ગ', 'go, gate'],
  ['gha', 'ઘ', 'egg'],
  ['ca', 'ચ', 'catch'],
  ['cha', 'છ', 'khaki'],
  ['ja', 'જ', 'jack'],
  ['jha', 'ઝ', 'hedgehog emphasised version of જ'],
  ['ta', 'ટ', 'court, train'],
  ['tha', 'ઠ', 'emphasised retroflex version of ટ'],
  ['da', 'ડ', 'somewhat like murder'],
  ['dha', 'ઢ', 'somewhat like guardhouse'],
  ['ta', 'ત', 'stop, stay'],
  ['tha', 'થ', 'emphasised version of ત'],
  ['da', 'દ', 'dog, breadth'],
  ['dha', 'ધ', 'adhere'],
  ['pa', 'પ', 'span, spade'],
  ['pha', 'ફ', "pan, or 'f', afraid"],
  ['ba', 'બ', 'bat'],
  ['bha', 'ભ', 'abhor'],
  ['ṅa', 'ઙ', 'bank, sing, velar nasal version'],
  ['ña', 'ઞ', 'canyon, palatal nasal version'],
  ['ṇa', 'ણ', 'somewhat like burner, retroflex nasal version'],
  ['na', 'ન', 'not, no'],
  ['ma', 'મ', 'much, me'],
  ['śa', 'શ', 'sheep'],
  ['ṣa', 'ષ', 'somewhat like worship'],
  ['sa', 'સ', 'sat, sue'],
  ['ra', 'ર', 'butter (American English)'],
  ['la', 'લ', 'leaf'],
  ['ḷa', 'ળ', 'somewhat like Merlin, retroflex lateral version'],
  ['ya', 'ય', 'yak, palatal semi-vowel'],
  ['va', 'વ', "vine but somewhere between 'v' and 'w'"],
  ['ha', 'હ', 'ahead'],
  ['kṣa', 'ક્ષ', 'ksa'],
  ['jña', 'જ્ઞ', 'gña'],
];

export default consonants;
